CC:=gcc
open_addressing: open_addressing.o main_open_addressing.o
double_hashing: double_hashing.o main_double_hashing.o         #add
	gcc double_hashing.o main_double_hashing.o -o double_hashing -lwinmm