CC = gcc
selection_sort: main_selection_sort.o selection_sort.o sort_util.o
insertion_sort: main_insertion_sort.o insertion_sort.o sort_util.o
heap_sort: main_heap_sort.o heap_sort.o sort_util.o
quick_sort: main_quick_sort.o quick_sort.o sort_util.o